apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
       app: myapp
       training: gitops-basics
    spec:
      containers:
      - image: nginx
        name: nginx:latest
        volumeMounts: 
        - name: config-volume 
          mountPath: /usr/share/nginx/html 
      volumes: 
      - name: config-volume 
        configMap: 
           name: myapp
