apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: new-cm-myapp 
data:
   setting: value
   index.html: |
     <html>
     <h1>Welcome</h1>
     </br>
     <h1>Hi! This is a test configmap Index file </h1>
     <h1>Hi! This is a test upgrade</h1>
     </html>
